# Generated by Django 3.2.5 on 2021-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210712_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='image',
            field=models.ImageField(upload_to='image/img_icecream'),
        ),
    ]
