# Generated by Django 3.2.5 on 2021-07-12 11:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210712_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('2'), max_digits=5),
        ),
    ]
