# Generated by Django 3.2.5 on 2021-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_icecream_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='image',
            field=models.ImageField(upload_to='images/icecream'),
        ),
    ]
